### ISSUE TITLE
Deprecated machines for picolibc?

### ISSUE THREAD

**Issue by jserv** [keith-packard/picolibc#11]
At present, there are 57 machines listed in directory `newlib/libc/machine/`. But I have no idea how many targets of them are really supported by picolibc along with `picocrt`. Is it worth to leave unsupported targets?

**Comment by mithro** [comment]
I would actually love to use picolibc on our FPGA soft cores and thus love to see the following supported (in order of my priority);
 * rv32
 * rv64
 * ppc64le
 * arm
 * ppc32
 * arm64
 * or1k
 * lm32
 * sh2 + sh4

**Comment by keith-packard** [comment]
I'd like to leave the library code for these architectures around -- it makes merging newlib changes easier so that we can be prepared for supporting those when possible. Adding support for a new architecture for picolibc is mostly a matter of creating the meson build files. Testing those requires a suitable toolchain, so if you've got compilers for your target architectures, you should be able to add the meson bits pretty quickly.

I've added the list of currently supported architectures to the README.md, along with a short description of the tasks necessary to add more architecture support. I think that's sufficient for now.
